### ISSUE TITLE
Github Actions Pipeline: First Steps

### ISSUE THREAD

**Issue by JD-Russo** [cse110-sp23-group12/cse110-sp23-group12#1]
# From Push to Build
- Set up our organization's Github Actions so that when somebody pushes code, it builds it on our repo! (idk what build even means tho lol, but that's for you guys to figure out/already know prolly)

**Comment by brandonszeto** [comment]
[Created Workflow Directoroy](https://github.com/cse110-sp23-group12/cse110-sp23-group12/commit/774ca0e47ffa5b6960a2c5aef8eda47827e36b59)
