### ISSUE TITLE
User experience: animations

### ISSUE THREAD

**Issue by AnniePhan02** [cse110-sp23-group12/cse110-sp23-group12#20]
Add animations and a nice appearance to the project that we have so far (might be done in sprint 2) but want to do within sprint 3
- add an animation to the fortune cookie cracking

**Comment by brandonszeto** [comment]
## Our design currently on Figma:

<img width="511" alt="image" src="https://github.com/cse110-sp23-group12/cse110-sp23-group12/assets/99768694/4c1725f0-fb10-4da4-aed0-c3ad300dc67b">

**Comment by joy002** [comment]
Our loading page animation:
<img width="585" alt="loading1" src="https://github.com/cse110-sp23-group12/cse110-sp23-group12/assets/73975897/ec861d01-5849-4268-9dab-2b16726f18a1">
<img width="584" alt="loading2" src="https://github.com/cse110-sp23-group12/cse110-sp23-group12/assets/73975897/adb5c9ef-fb0d-4fb8-bc23-f2f11d47f156">
<img width="584" alt="loading3" src="https://github.com/cse110-sp23-group12/cse110-sp23-group12/assets/73975897/6526a299-082f-4339-ab35-276c8027f990">
<img width="583" alt="loading4" src="https://github.com/cse110-sp23-group12/cse110-sp23-group12/assets/73975897/da08eb8c-aa2d-4ace-9988-6b93bd4051c5">
<img width="584" alt="loading5" src="https://github.com/cse110-sp23-group12/cse110-sp23-group12/assets/73975897/e2e91561-15b2-448a-a1b7-e0d53b6d5512">

**Comment by joy002** [comment]
Working on background:
Here are all the options:

<img width="758" alt="Screenshot 2023-06-05 at 4 42 09 PM" src="https://github.com/cse110-sp23-group12/cse110-sp23-group12/assets/73975897/63c26ee4-9ac8-49db-a8c6-95df89789792">

**Comment by wingchan852** [comment]
create cracking animation v1 38d011a3208c161e27a0251c9b6d273603eee050

**Comment by wingchan852** [comment]
new cracking animation on new UI f0bb7a2f903eefea18fe26f9eb04add2d617e5ce 860d31fd476b47e95b6c6ec243a6df3407095bc8 2d4b8af7b07eafbc1fcc9464e2a8b1ba089191b9
![ezgif com-video-to-gif](https://github.com/cse110-sp23-group12/cse110-sp23-group12/assets/66709835/ad1912c8-4c37-4363-8b7b-3ae3219d5ac6)
