### ISSUE TITLE
Code quality: JSDoc comments

### ISSUE THREAD

**Issue by AnniePhan02** [cse110-sp23-group12/cse110-sp23-group12#21]
Add in comments in our code about out functions and variables to explain what our code is doing

**Comment by brandonszeto** [comment]
Added JSDocs comments to display.js:

See https://github.com/cse110-sp23-group12/cse110-sp23-group12/commit/09bbeaae590840bcd3ca0bd36e03b059ccb177cc

**Comment by brandonszeto** [comment]
Added JSDocs comments to backup.js:

See https://github.com/cse110-sp23-group12/cse110-sp23-group12/commit/1cf88f2b4fc5d6d76bbeafc8b19058a4e4755898

**Comment by brandonszeto** [comment]
Added JSDocs comments to main.js:

See https://github.com/cse110-sp23-group12/cse110-sp23-group12/commit/801e7ba977a9cbe5ff63cb986ab07686d73bff09

**Comment by brandonszeto** [comment]
Added JSDocs comments to request.js

See https://github.com/cse110-sp23-group12/cse110-sp23-group12/commit/745d1ee6649a7018ed4397576039ca6339ef06c3

**Comment by brandonszeto** [comment]
Added JSDocs comments to server.js

See https://github.com/cse110-sp23-group12/cse110-sp23-group12/commit/be00ad8169f836df1be98d693f4ceb5c256e23c0

**Comment by brandonszeto** [comment]
Added JSDocs comments to utils.js

See https://github.com/cse110-sp23-group12/cse110-sp23-group12/commit/e8e38e103422fe5e82e7b00f9d5104a7f58ef0d5

**Comment by scripe2022** [comment]
resolved
