### ISSUE TITLE
Browser Compatibility: safari, chrome, etc

### ISSUE THREAD

**Issue by AnniePhan02** [cse110-sp23-group12/cse110-sp23-group12#24]
On different browsers, our app displays differently

**Comment by brandonszeto** [comment]
Current chrome responsiveness:
https://github.com/cse110-sp23-group12/cse110-sp23-group12/assets/99768694/d7db988f-b7ac-475c-a756-751f367c0f59

**Comment by brandonszeto** [comment]
Current mobile responsiveness:


[video](https://github.com/cse110-sp23-group12/cse110-sp23-group12/assets/99768694/6e1a0623-a606-4290-9a15-661e445a6032)

**Comment by brandonszeto** [comment]
Current Safari responsiveness:


[video](https://github.com/cse110-sp23-group12/cse110-sp23-group12/assets/99768694/2310c3f6-569c-4137-a95b-4922e2813fb5)

**Comment by brandonszeto** [comment]
Exhibits unexpected behavior when interacting between different screen sizes
