### ISSUE TITLE
Create custom fortune cards

### ISSUE THREAD

**Issue by Niklichang** [cse110-sp23-group12/cse110-sp23-group12#27]
Create fortune-cookie themed fortune cards based on the card themes: Joker, magician, emperor, etc.

**Comment by brandonszeto** [comment]
Current progress:

[Google slides w/ designs](https://docs.google.com/presentation/d/16ANYIu_7Rpv_H4ijWdhOxMq8305VwWiigIVaYyOzNTg/edit#slide=id.g250b1b14183_0_113)

<img width="961" alt="image" src="https://github.com/cse110-sp23-group12/cse110-sp23-group12/assets/99768694/4b22238e-32a2-4b13-8602-05e7978f0bd7">

<img width="950" alt="image" src="https://github.com/cse110-sp23-group12/cse110-sp23-group12/assets/99768694/4c3d82c4-513b-461d-a5bf-812286096924">

<img width="971" alt="image" src="https://github.com/cse110-sp23-group12/cse110-sp23-group12/assets/99768694/1724bbb0-ec5f-45e9-96c4-c23651fd20bb">

<img width="954" alt="image" src="https://github.com/cse110-sp23-group12/cse110-sp23-group12/assets/99768694/93b1197b-5bf0-4926-a4fc-5dcdb0f7c82c">
