### ISSUE TITLE
Sound setting should be consistent for every page

### ISSUE THREAD

**Issue by joy002** [cse110-sp23-group12/cse110-sp23-group12#39]
Issue: if turn on music on main page, second page's music setting should be default turn on too.

**Comment by maxrivett** [comment]
https://github.com/cse110-sp23-group12/cse110-sp23-group12/commit/3fae2be0495e0ff8303a88fc65adeac5ced314ef
https://github.com/cse110-sp23-group12/cse110-sp23-group12/commit/4553122cf6557ff98e2242516f0008216a4b0bd2
