### ISSUE TITLE
Github Actions Pipeline: Third Steps

### ISSUE THREAD

**Issue by JD-Russo** [cse110-sp23-group12/cse110-sp23-group12#6]
# Style Checking
- We are going to need consistent style amongst our code. 
- Part of this could mean using a linter in our pipeline, or creating a vs code set of style presets for everybody to use, or both.

**Comment by brandonszeto** [comment]
See merged pull request [#9](https://github.com/cse110-sp23-group12/cse110-sp23-group12/pull/9)
